### ISSUE TITLE
Unhandled exception. System.Reflection.TargetParameterCountException: Parameter count mismatch

### ISSUE THREAD

**Issue by ShakirPlayZ** [deluvas1911/saltychat-altv#22]
Hi all,

i uploaded the content of resource folder.
But it wont start. It gives me that following Error. 
Have you any Hints for that?

Files from: https://github.com/Salt-V/saltychat-altv

[csharp-module] Checking dependencies... this might take a few minutes...
Unhandled exception. System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at AltV.Net.Host.Host.InitAltVAssembly(Assembly altVNetAssembly, LibArgs libArgs, AssemblyLoadContext resourceAssemblyLoadContext, Dictionary`2 cApiFuncTable, String resourceName)
   at AltV.Net.Host.Host.ExecuteResource(IntPtr arg, Int32 argLength)
Server process exited with code 3762504530

**Comment by taker99** [comment]
Hello, I have the same problem. Is there a solution?

**Comment by ShakirPlayZ** [comment]
I asked Jonasesser for his SaltyChat. Maybe he will give to you too.
His Solution worked like a Charm.
His Discord: j0n4s#8301

**Comment by LorianAtashi01** [comment]
That seems like a problem with outdated packages. No Solution else needed for that. Just update the packages for the project.

**Comment by Statuefisch9194** [comment]
I updated everything but it still does not work.

maybe u can give some more info :)

**Comment by ShakirPlayZ** [comment]
You can use this (but there is no Private Support for this)
[https://github.com/ShakirPlayZ/altv-saltychat](https://github.com/ShakirPlayZ/altv-saltychat)

**Comment by LorianAtashi01** [comment]
@Statuefisch9194 i'm gonna update today the repo and upload an release. Sorry for responding that late but yeah private life is sometimes getting me to much :) @ShakirPlayZ if you use this version as a "own" verison please give the credits on your README to @deluvas1911, since he did a good Job :)

**Comment by ShakirPlayZ** [comment]
> @Statuefisch9194 i'm gonna update today the repo and upload an release. Sorry for responding that late but yeah private life is sometimes getting me to much :) @ShakirPlayZ if you use this version as a "own" verison please give the credits on your README to @deluvas1911, since he did a good Job :)

You´re right. Thanks reminding me
