### ISSUE TITLE
Altv neuste Version 

### ISSUE THREAD

**Issue by Dergebrochene512** [deluvas1911/saltychat-altv#7]
Moin erst mal geile arbeit die sie machen 

So nun zum Problem wen ich saltychat Aufenthalt server update startet der server nicht mehr und es kommt der fehler 

Unbehandelte Ausnahme erhalten von: AltV.Net.Exceptions.IllegalThreadException: CheckIfEntityExists from AltV.Net.Elements.Entities.Player hat im falschen Thread mit Name und ID 29 aufgerufen

   at AltV.Net.Elements.Entities.BaseObject.CheckIfCallIsValid(String callerName)

   bei AltV.Net.Elements.Entities.Entity.CheckIfEntityExists()

   bei AltV.Net.Elements.Entities.Player.get_Position()

   at SaltyChat.Server.VoiceManager.OnServerEnablePlayer(IPlayer player, Int32 charId) in C:\Users\Administrator\Desktop\Infinity-city-V3 1\Infinity-city-V3 1\Mappe\Altv-Roleplay\SaltyServer\VoiceManager.cs :Zeile 216

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Objektstatus)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext ExecutionContext, Action`1 Callback, TState& Zustand)

   bei System.Threading.QueueUserWorkItemCallback.Execute()

   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
[03:30:12] < ==== UNHANDLED AUSNAHME ==== > 

 Unbehandelte Ausnahme erhalten von: AltV.Net.Exceptions.IllegalThreadException: CheckIfEntityExists from AltV.Net.Elements.Entities.Player hat im falschen Thread mit Name und ID 29 aufgerufen

   at AltV.Net.Elements.Entities.BaseObject.CheckIfCallIsValid(String callerName)

   bei AltV.Net.Elements.Entities.Entity.CheckIfEntityExists()

   bei AltV.Net.Elements.Entities.Player.get_Position()

   at SaltyChat.Server.VoiceManager.OnServerEnablePlayer(IPlayer player, Int32 charId) in C:\Users\Administrator\Desktop\Infinity-city-V3 1\Infinity-city-V3 1\Mappe\Altv-Roleplay\SaltyServer\VoiceManager.cs :Zeile 216

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Objektstatus)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext ExecutionContext, Action`1 Callback, TState& Zustand)

   bei System.Threading.QueueUserWorkItemCallback.Execute()

   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
[03:30:12] < ==== UNHANDLED AUSNAHME ==== > 

 Unbehandelte Ausnahme erhalten von: AltV.Net.Exceptions.IllegalThreadException: CheckIfEntityExists from AltV.Net.Elements.Entities.Player hat im falschen Thread mit Name und ID 29 aufgerufen

   at AltV.Net.Elements.Entities.BaseObject.CheckIfCallIsValid(String callerName)

   bei AltV.Net.Elements.Entities.Entity.CheckIfEntityExists()

   bei AltV.Net.Elements.Entities.Player.get_Position()

   at SaltyChat.Server.VoiceManager.OnServerEnablePlayer(IPlayer player, Int32 charId) in C:\Users\Administrator\Desktop\Infinity-city-V3 1\Infinity-city-V3 1\Mappe\Altv-Roleplay\SaltyServer\VoiceManager.cs :Zeile 216

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Objektstatus)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext ExecutionContext, Action`1 Callback, TState& Zustand)

   bei System.Threading.QueueUserWorkItemCallback.Execute()

   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
[03:30:12] < ==== UNHANDLED AUSNAHME ==== > 

 Unbehandelte Ausnahme erhalten von: AltV.Net.Exceptions.IllegalThreadException: CheckIfEntityExists from AltV.Net.Elements.Entities.Player hat im falschen Thread mit Name und ID 29 aufgerufen

   at AltV.Net.Elements.Entities.BaseObject.CheckIfCallIsValid(String callerName)

   bei AltV.Net.Elements.Entities.Entity.CheckIfEntityExists()

   bei AltV.Net.Elements.Entities.Player.get_Position()

   at SaltyChat.Server.VoiceManager.OnServerEnablePlayer(IPlayer player, Int32 charId) in C:\Users\Administrator\Desktop\Infinity-city-V3 1\Infinity-city-V3 1\Mappe\Altv-Roleplay\SaltyServer\VoiceManager.cs :Zeile 216

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Objektstatus)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext ExecutionContext, Action`1 Callback, TState& Zustand)

   bei System.Threading.QueueUserWorkItemCallback.Execute()

   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

Und wenn es dann doch mal geht geht der server aus wen zwei Spieler im voice sind und da kommt der fehler 

den bekomme ich wen  SaltyChat Started 

WARNING: AltV.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null is not optimized and might not provide best possible runtime performance.
WARNING: AltV.Net.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null is not optimized and might not provide best possible runtime performance.

So lange ich alleine auf dem Server bin geht alles sobald einer drauf kommt geht nix mehr heißt der server geht aus ohne saltychat auf dem server aktive zu haben geht auch alles aber halt ohne voice 

LG und tut mir leid wen es nicht hier her gehört

**Comment by deluvas1911** [comment]
kannst es mal mit [der](https://github.com/deluvas1911/saltychat-altv/releases/tag/1.2.0) version versuchen?

**Comment by Dergebrochene512** [comment]
Mache 8ch sofort sobald ich wach bin

**Comment by Dergebrochene512** [comment]
So ich habe es jetzt getestet server geht nicht mehr aus aber toggelrange geht nicht

**Comment by deluvas1911** [comment]
Schick mir mal ne Discord FA. Einfach deluvas im Salty oder AltV discord suchen
